services:
  db:
    image: mysql:8
    container_name: project_domina
    environment:
      MYSQL_DATABASE: project_domina
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"  
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    restart: unless-stopped

  auth-service:
    build:
      context: ./api/auth-service
    container_name: project_domina-auth-service
    depends_on:
      - db
    ports:
      - "4000:4000"
    restart: unless-stopped

  task-service:
    build:
      context: ./api/task-service
    container_name: project_domina-task-service
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./app
    container_name: project_domina-frontend
    ports:
      - "5173:80"
    depends_on:
      - auth-service
      - task-service
    restart: unless-stopped

volumes:
  db_data:
